server:
  port: 8888
  
eureka:  instance:    hostname: register
    prefer-ip-address: true
    metadata-map:      user.name: ${security.user.name}
      user.password: ${security.user.password}
      
  client:    service-url:      defaultZone: http://user:${REGISTER_SERVER_PASSWORD:password}@register:8761/eureka/
      
      
spring:  cloud:    config:      server:        git:          uri: https://github.com/OyXw1/spring-boot-cloud
          search-paths:          - config-repository
  rabbitmq:    host: rabbitmq
    
security:  user:    name: user
    password: ${CONFIGS_SERVER_PASSWORD:password}