logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error
    
server:  port: 8040
  
turbine:  stream:    port: 8041
    
eureka:  instance:    hostname: register
    prefer-ip-address: true
    metadata-map:      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:    service-url:      defaultZone: http://user:${REGISTER_SERVER_PASSWORD:password}@register:8761/eureka/
      
spring:  rabbitmq:    host: rabbitmq
  boot:    admin:      routes:        endpoints:        - env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:        clusters:        - default
        location: http://monitors:${turbine.stream.port}
        
security:  user:    name: admin
    password: ${MONITORS_SERVER_PASSWORD:admin}